"""ForgeRL Reward System — Multi-signal reward with dense shaping + sparse terminal.

The reward function is the core of the RL environment. It must:
1. Provide dense per-step signals to guide learning (reward shaping)
2. Provide a large sparse terminal reward tied to actual code quality
3. Scale with token output (Mercor sub-theme)
4. Penalize inefficiency and invalid actions
5. Reward oversight catches and recovery success

Reward components:
  - Phase Progress: +0.5 for each successful phase transition
  - Task Completion: +2.0 for each task that passes all tests
  - Recovery Success: +1.0 for recovering from a failure
  - Oversight Catch: +0.5 for each real issue caught by oversight
  - Code Quality: Terminal bonus scaled by test pass rate and quality score
  - Token Scaling: Reward proportional to useful output tokens (Mercor)
  - Step Cost: -0.01 per step to encourage efficiency
  - Invalid Action: -1.0 for taking an invalid action in current state
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional

from forge_env.models import (
    ActionType,
    ForgeAction,
    ForgeObservation,
    OversightReport,
    ProjectSnapshot,
    TaskProgressSummary,
)


@dataclass
class RewardSignal:
    """Decomposed reward signal for logging and analysis."""

    total: float = 0.0
    phase_progress: float = 0.0
    task_completion: float = 0.0
    recovery_success: float = 0.0
    oversight_bonus: float = 0.0
    code_quality_terminal: float = 0.0
    token_scaling: float = 0.0
    step_cost: float = 0.0
    invalid_action_penalty: float = 0.0
    efficiency_bonus: float = 0.0
    reviewer_satisfaction: float = 0.0

    def compute_total(self) -> float:
        self.total = (
            self.phase_progress
            + self.task_completion
            + self.recovery_success
            + self.oversight_bonus
            + self.code_quality_terminal
            + self.token_scaling
            + self.step_cost
            + self.invalid_action_penalty
            + self.efficiency_bonus
            + self.reviewer_satisfaction
        )
        return self.total


class ForgeRewardCalculator:
    """Composite reward calculator with dense shaping and sparse terminal rewards.

    The calculator maintains state across steps within an episode to track
    progress-based rewards (e.g., "new phase reached" vs "already visited").
    """

    # ── Dense per-step rewards ──
    PHASE_TRANSITION_REWARD = 0.5
    TASK_COMPLETION_REWARD = 2.0
    RECOVERY_SUCCESS_REWARD = 1.0
    OVERSIGHT_CATCH_REWARD = 0.5
    VALID_DELEGATION_REWARD = 0.1

    # ── Penalties ──
    INVALID_ACTION_PENALTY = -1.0
    UNNECESSARY_RETRY_PENALTY = -0.3
    STEP_COST = -0.01
    WRONG_PHASE_PENALTY = -0.5
    REPEATED_ACTION_PENALTY = -0.2

    # ── Sparse terminal rewards ──
    FULL_SUCCESS_BONUS = 20.0
    PARTIAL_SUCCESS_BONUS = 5.0
    TEST_PASS_RATE_MULTIPLIER = 10.0
    CODE_QUALITY_MULTIPLIER = 5.0
    EFFICIENCY_MULTIPLIER = 3.0

    # ── Mercor token scaling ──
    TOKEN_REWARD_PER_1K = 0.1  # Reward per 1000 useful output tokens

    # ── Reviewer satisfaction ──
    REVIEWER_SATISFACTION_MULTIPLIER = 2.0

    def __init__(self):
        self._visited_phases: set[str] = set()
        self._completed_task_ids: set[int] = set()
        self._total_steps: int = 0
        self._total_tokens: int = 0
        self._consecutive_invalid: int = 0
        self._last_action: Optional[ActionType] = None
        self._recovery_attempts: int = 0
        self._successful_recoveries: int = 0

    def reset(self):
        """Reset reward state for a new episode."""
        self._visited_phases.clear()
        self._completed_task_ids.clear()
        self._total_steps = 0
        self._total_tokens = 0
        self._consecutive_invalid = 0
        self._last_action = None
        self._recovery_attempts = 0
        self._successful_recoveries = 0

    def compute_step_reward(
        self,
        action: ForgeAction,
        prev_obs: ForgeObservation,
        curr_obs: ForgeObservation,
        action_valid: bool,
        is_terminal: bool,
        tokens_generated: int = 0,
    ) -> RewardSignal:
        """Compute the reward for a single step.

        Args:
            action: The action taken by the meta-agent.
            prev_obs: Observation before the action.
            curr_obs: Observation after the action.
            action_valid: Whether the action was valid in the current state.
            is_terminal: Whether this step ends the episode.
            tokens_generated: Number of tokens generated by sub-agents this step.

        Returns:
            RewardSignal with decomposed reward components.
        """
        self._total_steps += 1
        self._total_tokens += tokens_generated
        signal = RewardSignal()

        # ── 1. Step cost (always applied) ──
        signal.step_cost = self.STEP_COST

        # ── 2. Invalid action penalty ──
        if not action_valid:
            self._consecutive_invalid += 1
            # Escalating penalty for consecutive invalid actions
            signal.invalid_action_penalty = (
                self.INVALID_ACTION_PENALTY * self._consecutive_invalid
            )
            signal.compute_total()
            self._last_action = action.action_type
            return signal
        else:
            self._consecutive_invalid = 0

        # ── 3. Phase transition reward ──
        if curr_obs.current_phase != prev_obs.current_phase:
            if curr_obs.current_phase not in self._visited_phases:
                signal.phase_progress = self.PHASE_TRANSITION_REWARD
                self._visited_phases.add(curr_obs.current_phase)

        # ── 4. Task completion reward ──
        new_completed = (
            curr_obs.task_progress.completed - prev_obs.task_progress.completed
        )
        if new_completed > 0:
            for _ in range(new_completed):
                signal.task_completion += self.TASK_COMPLETION_REWARD

        # ── 5. Recovery success reward ──
        if action.action_type == ActionType.DELEGATE_RECOVERY:
            self._recovery_attempts += 1
        if (
            prev_obs.error_context
            and not curr_obs.error_context
            and curr_obs.last_agent_output.success
        ):
            signal.recovery_success = self.RECOVERY_SUCCESS_REWARD
            self._successful_recoveries += 1

        # ── 6. Oversight bonus ──
        if (
            curr_obs.oversight_report
            and curr_obs.oversight_report.issues_found > 0
        ):
            signal.oversight_bonus = (
                self.OVERSIGHT_CATCH_REWARD
                * curr_obs.oversight_report.critical_issues
            )

        # ── 7. Valid delegation reward (small) ──
        if action.action_type.value.startswith("delegate_") and action_valid:
            signal.phase_progress += self.VALID_DELEGATION_REWARD

        # ── 8. Repeated action penalty ──
        if (
            action.action_type == self._last_action
            and action.action_type
            not in (ActionType.DELEGATE_CODER, ActionType.DELEGATE_QA)
        ):
            signal.invalid_action_penalty += self.REPEATED_ACTION_PENALTY

        # ── 9. Token scaling (Mercor) ──
        if tokens_generated > 0:
            signal.token_scaling = (
                tokens_generated / 1000.0 * self.TOKEN_REWARD_PER_1K
            )

        # ── 10. Reviewer satisfaction ──
        if (
            curr_obs.reviewer_feedback
            and curr_obs.reviewer_feedback.satisfaction_score > 0
        ):
            signal.reviewer_satisfaction = (
                curr_obs.reviewer_feedback.satisfaction_score
                * self.REVIEWER_SATISFACTION_MULTIPLIER
            )

        # ── 11. Terminal reward ──
        if is_terminal:
            signal = self._compute_terminal_reward(signal, curr_obs)

        self._last_action = action.action_type
        signal.compute_total()
        return signal

    def _compute_terminal_reward(
        self, signal: RewardSignal, final_obs: ForgeObservation
    ) -> RewardSignal:
        """Compute sparse terminal reward based on final project quality."""
        progress = final_obs.task_progress

        # Full success: all tasks completed
        if progress.total_tasks > 0 and progress.completed == progress.total_tasks:
            signal.code_quality_terminal += self.FULL_SUCCESS_BONUS
        elif progress.completed > 0:
            # Partial success scaled by completion rate
            completion_rate = progress.completed / max(progress.total_tasks, 1)
            signal.code_quality_terminal += (
                self.PARTIAL_SUCCESS_BONUS * completion_rate
            )

        # Test pass rate bonus
        project = final_obs.project_state
        if project.tests_passed + project.tests_failed > 0:
            pass_rate = project.tests_passed / (
                project.tests_passed + project.tests_failed
            )
            signal.code_quality_terminal += (
                pass_rate * self.TEST_PASS_RATE_MULTIPLIER
            )

        # Oversight quality score
        if final_obs.oversight_report:
            signal.code_quality_terminal += (
                final_obs.oversight_report.quality_score
                * self.CODE_QUALITY_MULTIPLIER
            )

        # Efficiency bonus: fewer steps = better
        if final_obs.max_steps > 0:
            efficiency = 1.0 - (
                final_obs.step_count / final_obs.max_steps
            )
            if efficiency > 0.5:  # Only reward if reasonably efficient
                signal.efficiency_bonus = (
                    efficiency * self.EFFICIENCY_MULTIPLIER
                )

        # Recovery effectiveness
        if self._recovery_attempts > 0:
            recovery_rate = (
                self._successful_recoveries / self._recovery_attempts
            )
            signal.recovery_success += recovery_rate * 2.0

        return signal

    def get_episode_stats(self) -> dict:
        """Return statistics about the current episode's rewards."""
        return {
            "total_steps": self._total_steps,
            "total_tokens": self._total_tokens,
            "phases_visited": len(self._visited_phases),
            "tasks_completed": len(self._completed_task_ids),
            "recovery_attempts": self._recovery_attempts,
            "successful_recoveries": self._successful_recoveries,
            "consecutive_invalid": self._consecutive_invalid,
        }
