"""Docker Builder — Generates Docker artifacts for the generated project.

Satisfies optional extended requirements: Dockerization of the generated project.
"""

from pathlib import Path
from typing import Optional

from forgeai.core.activity_logger import ActivityLogger


class DockerBuilder:
    """Generates Dockerfile and docker-compose.yml for the generated project."""

    def __init__(self, project_dir: str, logger: Optional[ActivityLogger] = None):
        self._project_dir = Path(project_dir).resolve()
        self._logger = logger

    def generate_docker_files(self, base_image: str = "python:3.11-slim"):
        """Generate Dockerfile and docker-compose.yml."""
        
        # 1. Generate Dockerfile
        dockerfile_content = f"""# Auto-generated by ForgeAI
FROM {base_image}

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY . .

# Set environment variables
ENV PYTHONPATH=/app
ENV PYTHONUNBUFFERED=1

# Default port for FastAPI projects
EXPOSE 8000

# Run the application
CMD ["python", "src/main.py"]
"""
        dockerfile_path = self._project_dir / "Dockerfile"
        with open(dockerfile_path, "w", encoding="utf-8") as f:
            f.write(dockerfile_content)

        # 2. Generate docker-compose.yml
        compose_content = f"""# Auto-generated by ForgeAI
version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./test.db
    volumes:
      - .:/app
"""
        compose_path = self._project_dir / "docker-compose.yml"
        with open(compose_path, "w", encoding="utf-8") as f:
            f.write(compose_content)

        if self._logger:
            self._logger.info("DockerBuilder", "Generated Dockerfile and docker-compose.yml")
            self._logger.file_write("DockerBuilder", "Dockerfile")
            self._logger.file_write("DockerBuilder", "docker-compose.yml")
