"""SDLC RL Environment — OpenEnv-compatible environment for code generation.

Implements the standard OpenEnv interface:
    reset()  → observation dict
    step()   → (observation, reward, done, info)
    state()  → current environment state

The environment wraps a curriculum of coding tasks.  The agent (LLM) receives
a task description and produces Python code.  The code is executed against
pytest tests.  Reward is a composite of 5 independent signals.

This design maps directly to the hackathon's recommended pattern:
    Environment → verifier/reward functions → TRL trainer → Unsloth

Anti-cheat measures:
    - Sandboxed subprocess execution (no network, no file writes)
    - Hard penalty for detected reward-hacking patterns
    - Timeout enforcement per episode
    - Episode-level action logging for audit
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass
from typing import Optional

from forgeai.rl.curriculum import CodingTask, CurriculumManager, DifficultyLevel
from forgeai.rl.models import SDLCObservation
from forgeai.rl.reward_functions import RewardBreakdown, RewardEngine
from forgeai.rl.verifier import CodeVerifier, VerificationResult


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

@dataclass
class EnvironmentConfig:
    """Hyperparameters for the standalone (non-MCP) training environment."""
    timeout_seconds: int = 10
    max_steps_per_episode: int = 1      # Single-step: one code generation per episode
    start_difficulty: DifficultyLevel = DifficultyLevel.EASY
    include_solution_hint: bool = False


# ---------------------------------------------------------------------------
# Step info
# ---------------------------------------------------------------------------

@dataclass
class SDLCStepInfo:
    """Extra info returned by step() — for monitoring and debugging."""
    episode_id: str
    task_id: str
    difficulty: str
    reward_breakdown: dict
    verification: dict
    step: int
    done: bool


# ---------------------------------------------------------------------------
# Main Environment
# ---------------------------------------------------------------------------

class SDLCEnvironment:
    """OpenEnv-compatible SDLC RL environment.

    Episode lifecycle:
        obs = env.reset()             # Sample a new task
        obs, reward, done, info = env.step(code)   # Execute code
        # done=True after first successful step or max_steps exceeded

    OpenEnv compatibility:
        reset()     → dict  (serialisable observation)
        step(action)→ tuple[dict, float, bool, dict]
        state()     → dict  (full environment state for debugging)
    """

    def __init__(self, config: Optional[EnvironmentConfig] = None):
        self._cfg = config or EnvironmentConfig()
        self._verifier = CodeVerifier(timeout_seconds=self._cfg.timeout_seconds)
        self._reward_engine = RewardEngine(timeout_seconds=self._cfg.timeout_seconds)
        self._curriculum = CurriculumManager(start_level=self._cfg.start_difficulty)

        # Episode state
        self._episode_id: str = ""
        self._current_task: Optional[CodingTask] = None
        self._step_count: int = 0
        self._last_observation: Optional[SDLCObservation] = None
        self._episode_log: list[dict] = []

        # Aggregate metrics
        self._total_episodes: int = 0
        self._total_rewards: list[float] = []

    # ── OpenEnv Interface ─────────────────────────────────────────────────

    def reset(self) -> dict:
        """Start a new episode: sample a task from the curriculum.

        Returns:
            Serialisable observation dict with keys:
                task_description, function_signature, test_code,
                previous_error, step, episode_id
        """
        self._episode_id = str(uuid.uuid4())[:8]
        self._step_count = 0
        self._episode_log = []

        self._current_task = self._curriculum.sample_task()

        obs = SDLCObservation(
            task_description=self._current_task.description,
            function_signature=self._current_task.function_signature,
            test_code=self._current_task.test_code,
            step=0,
            episode_id=self._episode_id,
        )
        self._last_observation = obs
        self._total_episodes += 1
        return self._obs_to_dict(obs)

    def step(self, action: str) -> tuple[dict, float, bool, dict]:
        """Execute the agent's code and return (observation, reward, done, info).

        Args:
            action: The Python code generated by the LLM.

        Returns:
            observation : dict — next observation (includes test error if failed)
            reward      : float — composite reward in [-1.0, 1.0]
            done        : bool — episode is complete
            info        : dict — full reward breakdown and verification details
        """
        if self._current_task is None:
            raise RuntimeError("Call reset() before step()")

        self._step_count += 1

        # ── Verify the generated code ──────────────────────────────────────
        verification: VerificationResult = self._verifier.verify(
            generated_code=action,
            test_code=self._current_task.test_code,
            task_signature=self._current_task.function_signature,
        )

        # ── Compute reward ─────────────────────────────────────────────────
        breakdown: RewardBreakdown = self._reward_engine.compute(
            result=verification,
            generated_code=action,
            expected_signature=self._current_task.function_signature,
        )
        reward = breakdown.total
        self._total_rewards.append(reward)

        # ── Record episode step ────────────────────────────────────────────
        step_log = {
            "episode_id": self._episode_id,
            "step": self._step_count,
            "task_id": self._current_task.task_id,
            "reward": reward,
            "breakdown": breakdown.to_dict(),
            "pass_rate": verification.pass_rate,
            "anti_cheat": verification.anti_cheat_violations,
        }
        self._episode_log.append(step_log)

        # ── Determine done ─────────────────────────────────────────────────
        done = (
            verification.success
            or self._step_count >= self._cfg.max_steps_per_episode
            or bool(verification.anti_cheat_violations)
        )

        if done:
            self._curriculum.record_result(
                success=verification.success,
                pass_rate=verification.pass_rate,
            )

        # ── Build next observation ────────────────────────────────────────
        error_context = ""
        if not verification.success and not verification.anti_cheat_violations:
            # Feed failure feedback back to the model
            error_context = (
                verification.stdout[-600:]
                if verification.stdout
                else verification.stderr[-600:]
            )

        next_obs = SDLCObservation(
            task_description=self._current_task.description,
            function_signature=self._current_task.function_signature,
            test_code=self._current_task.test_code,
            previous_error=error_context,
            step=self._step_count,
            episode_id=self._episode_id,
        )
        self._last_observation = next_obs

        info = SDLCStepInfo(
            episode_id=self._episode_id,
            task_id=self._current_task.task_id,
            difficulty=self._current_task.difficulty.value,
            reward_breakdown=breakdown.to_dict(),
            verification=verification.to_dict(),
            step=self._step_count,
            done=done,
        )

        return self._obs_to_dict(next_obs), reward, done, self._info_to_dict(info)

    def state(self) -> dict:
        """Return full environment state (for debugging and deployment health checks)."""
        return {
            "episode_id": self._episode_id,
            "current_task": self._current_task.task_id if self._current_task else None,
            "difficulty": self._curriculum.current_level.value,
            "step": self._step_count,
            "total_episodes": self._total_episodes,
            "mean_reward": (
                sum(self._total_rewards) / len(self._total_rewards)
                if self._total_rewards else 0.0
            ),
            "curriculum_stats": {
                "level": self._curriculum.current_level.value,
                "recent_success_rate": self._curriculum.stats.recent_success_rate,
                "total_episodes": self._curriculum.stats.total_episodes,
            },
        }

    # ── Prompt Helper ─────────────────────────────────────────────────────

    def get_prompt(self) -> str:
        """Return the LLM prompt for the current observation."""
        if self._last_observation is None:
            raise RuntimeError("Call reset() first")
        return self._last_observation.to_prompt()

    # ── Serialisation helpers ─────────────────────────────────────────────

    @staticmethod
    def _obs_to_dict(obs: SDLCObservation) -> dict:
        return {
            "task_description": obs.task_description,
            "function_signature": obs.function_signature,
            "test_code": obs.test_code,
            "previous_error": obs.previous_error,
            "step": obs.step,
            "episode_id": obs.episode_id,
            "prompt": obs.to_prompt(),
        }

    @staticmethod
    def _info_to_dict(info: SDLCStepInfo) -> dict:
        return {
            "episode_id": info.episode_id,
            "task_id": info.task_id,
            "difficulty": info.difficulty,
            "reward_breakdown": info.reward_breakdown,
            "verification": info.verification,
            "step": info.step,
            "done": info.done,
        }
